
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sevinc
 */
public class KargoSil extends javax.swing.JFrame {

    /**
     * Creates new form KargoSil
     */
    public KargoSil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        kargoSilIdText = new java.awt.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        kargoSilBilgiText = new javax.swing.JTextPane();
        kargoSilBilgiBtn = new javax.swing.JButton();
        kargoSilSilBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Kargo Id: ");

        jScrollPane2.setViewportView(kargoSilBilgiText);

        kargoSilBilgiBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kargoSilBilgiBtn.setText("Kargoyu Görüntele");
        kargoSilBilgiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kargoSilBilgiBtnActionPerformed(evt);
            }
        });

        kargoSilSilBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kargoSilSilBtn.setText("SİL");
        kargoSilSilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kargoSilSilBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("KARGO SİLME EKRANI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(kargoSilBilgiBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(kargoSilIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(342, Short.MAX_VALUE)
                    .addComponent(kargoSilSilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(145, 145, 145)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kargoSilIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(kargoSilBilgiBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(kargoSilSilBtn)
                    .addContainerGap(230, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kargoSilSilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kargoSilSilBtnActionPerformed
        // TODO add your handling code here:
        if (kargoSilIdText.getText().equals("") || kargoSilIdText.getText().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Bilgilerin Doğru Olduğundan Emin Olun.", "! Dikkat", HEIGHT);
            
        } else {
            ConnectionTrial ct = new ConnectionTrial();
            ct.deleteCargo(Integer.parseInt(kargoSilIdText.getText()));
        }
        kargoSilIdText.setText("");

    }//GEN-LAST:event_kargoSilSilBtnActionPerformed

    private void kargoSilBilgiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kargoSilBilgiBtnActionPerformed
        ConnectionTrial ct = new ConnectionTrial();
        if (kargoSilIdText.getText().equals("") || kargoSilIdText.getText().equals(" ") || ct.cargoS(Integer.parseInt(kargoSilIdText.getText())).length() == 2 ) {
            JOptionPane.showMessageDialog(null, "Bigilerin Eksiksiz Olduğundan Emin olun. \n"
                    + "Tekrar Deneyiniz.", "! Dikkat", HEIGHT);
        } else {
            
            
            kargoSilBilgiText.setText("İD    " + "ALICI ID    " + "GONDERİCİ ID    " + "ALICI ADRES     " + "GÖNDERİCİ ADRES    " + "KARGO KG   " + "\n" + ct.cargoS(Integer.parseInt(kargoSilIdText.getText())));
        }
        kargoSilIdText.setText("");
    }//GEN-LAST:event_kargoSilBilgiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KargoSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KargoSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KargoSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KargoSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KargoSil().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kargoSilBilgiBtn;
    private javax.swing.JTextPane kargoSilBilgiText;
    private java.awt.TextField kargoSilIdText;
    private javax.swing.JButton kargoSilSilBtn;
    // End of variables declaration//GEN-END:variables
}
