
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sevinc
 */
public class KullaniciEkran extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciEkran
     */
    public KullaniciEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        kullaniciEkranKargoIdText = new java.awt.TextField();
        kullaniciEkranBilgiGncBtn = new java.awt.Button();
        kullaniciEkranKargoBilgiBtn = new java.awt.Button();
        label3 = new java.awt.Label();
        bilgiEkran = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label1.setText("Kargo Bilgileri:");

        label2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label2.setText("Kargo İd Giriniz:");

        kullaniciEkranKargoIdText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        kullaniciEkranBilgiGncBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kullaniciEkranBilgiGncBtn.setLabel("Bilgilerimi Güncelle");
        kullaniciEkranBilgiGncBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciEkranBilgiGncBtnActionPerformed(evt);
            }
        });

        kullaniciEkranKargoBilgiBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kullaniciEkranKargoBilgiBtn.setLabel("Kargo Bilgilerini Gör");
        kullaniciEkranKargoBilgiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciEkranKargoBilgiBtnActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label3.setText("KULLANICI EKRAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kullaniciEkranBilgiGncBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(91, 91, 91)
                                .addComponent(kullaniciEkranKargoBilgiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(kullaniciEkranKargoIdText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bilgiEkran, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(163, 163, 163))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addGap(462, 462, 462)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(kullaniciEkranKargoIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bilgiEkran, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullaniciEkranBilgiGncBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kullaniciEkranKargoBilgiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(301, 301, 301)))
        );

        label1.getAccessibleContext().setAccessibleName(":");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciEkranBilgiGncBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciEkranBilgiGncBtnActionPerformed
        KullaniciBilgiGuncelle kbg = new KullaniciBilgiGuncelle();
        kbg.setVisible(true);
    }//GEN-LAST:event_kullaniciEkranBilgiGncBtnActionPerformed

    private void kullaniciEkranKargoBilgiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciEkranKargoBilgiBtnActionPerformed
        // TODO add your handling code here:
        ConnectionTrial ct = new ConnectionTrial();
        if (kullaniciEkranKargoIdText.getText().equals("") || kullaniciEkranKargoIdText.getText().equals(" ") || ct.cargoS(Integer.parseInt(kullaniciEkranKargoIdText.getText())).length() == 2) {
            JOptionPane.showMessageDialog(null, "Bigilerin Eksiksiz Olduğundan Emin olun. \n"
                    + "Tekrar Deneyiniz.", "! Dikkat", HEIGHT);
        } else {

           bilgiEkran.setText("İD    " + "ALICI ID    " + "GONDERİCİ ID    " + "ALICI ADRES     " + "GÖNDERİCİ ADRES    " + "KARGO KG   " + "\n" + ct.cargoS(Integer.parseInt(kullaniciEkranKargoIdText.getText())));
           
        }
       kullaniciEkranKargoIdText.setText("");
    }//GEN-LAST:event_kullaniciEkranKargoBilgiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea bilgiEkran;
    private java.awt.Button kullaniciEkranBilgiGncBtn;
    private java.awt.Button kullaniciEkranKargoBilgiBtn;
    private java.awt.TextField kullaniciEkranKargoIdText;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
