
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sevinc
 */
public class YoneticiEkran extends javax.swing.JFrame {

    /**
     * Creates new form YoneticiEkran
     */
    public YoneticiEkran() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kullaniciEkleBtn = new javax.swing.JButton();
        kullaniciSilBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        yoneticiEkrKrgBilgiText = new javax.swing.JTextPane();
        kargoListeleBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kargoAraText = new javax.swing.JTextField();
        kargoAraBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kargoEkleBtn = new javax.swing.JButton();
        KargoSilBtn = new javax.swing.JButton();
        yoneticiEkleBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        kullaniciEkleBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        kullaniciEkleBtn.setText("Kullanıcı Ekle");
        kullaniciEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciEkleBtnActionPerformed(evt);
            }
        });

        kullaniciSilBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        kullaniciSilBtn.setText("Kullanıcı Sil");
        kullaniciSilBtn.setPreferredSize(new java.awt.Dimension(123, 31));
        kullaniciSilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciSilBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(yoneticiEkrKrgBilgiText);

        kargoListeleBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        kargoListeleBtn.setText("Kargoları Listele");
        kargoListeleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kargoListeleBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Aranacak Kargo ID Girin:");

        kargoAraBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        kargoAraBtn.setText("ARA");
        kargoAraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kargoAraBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("DORUK KARGO");

        kargoEkleBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        kargoEkleBtn.setText("Kargo Ekle");
        kargoEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kargoEkleBtnActionPerformed(evt);
            }
        });

        KargoSilBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        KargoSilBtn.setText("Kargo Sil");
        KargoSilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KargoSilBtnActionPerformed(evt);
            }
        });

        yoneticiEkleBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        yoneticiEkleBtn.setText("Yönetici Ekle");
        yoneticiEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kullaniciSilBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kullaniciEkleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yoneticiEkleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(482, 482, 482)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kargoListeleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(kargoEkleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(KargoSilBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(98, 98, 98))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kargoAraText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kargoAraBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addGap(367, 367, 367))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kullaniciEkleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kullaniciSilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yoneticiEkleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kargoEkleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(KargoSilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kargoListeleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kargoAraText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kargoAraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)
                        .addGap(354, 354, 354)
                        .addComponent(jLabel2)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciEkleBtnActionPerformed
        KullaniciEkle ke = new KullaniciEkle();
        ke.setVisible(true);
    }//GEN-LAST:event_kullaniciEkleBtnActionPerformed

    private void kullaniciSilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciSilBtnActionPerformed
        KullaniciSil ks = new KullaniciSil();
        ks.setVisible(true);
        
    }//GEN-LAST:event_kullaniciSilBtnActionPerformed

    private void kargoListeleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kargoListeleBtnActionPerformed
        ConnectionTrial ct = new ConnectionTrial();

        yoneticiEkrKrgBilgiText.setText("İD    " + "ALICI ID    " + "GONDERİCİ ID    " + "ALICI ADRES     " + "GÖNDERİCİ ADRES    " + "KARGO KG   " + "\n" + ct.cargoS());


    }//GEN-LAST:event_kargoListeleBtnActionPerformed


    private void kargoAraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kargoAraBtnActionPerformed
        ConnectionTrial ct = new ConnectionTrial();

        if (kargoAraText.getText().equals("") || kargoAraText.getText().equals(" ") || ct.cargoS(Integer.parseInt(kargoAraText.getText())).length() == 2) {
            JOptionPane.showMessageDialog(null, "Bigilerin Eksiksiz Olduğundan Emin olun. \n"
                    + "Tekrar Deneyiniz.", "! Dikkat", HEIGHT);
        } else {

            yoneticiEkrKrgBilgiText.setText("İD    " + "ALICI ID    " + "GONDERİCİ ID    " + "ALICI ADRES     " + "GÖNDERİCİ ADRES    " + "KARGO KG   " + "\n" + ct.cargoS(Integer.parseInt(kargoAraText.getText())));
        }
        kargoAraText.setText("");
    }//GEN-LAST:event_kargoAraBtnActionPerformed

    private void kargoEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kargoEkleBtnActionPerformed
        // TODO add your handling code here:
        KargoEkle ke = new KargoEkle();
        ke.setVisible(true);
    }//GEN-LAST:event_kargoEkleBtnActionPerformed

    private void KargoSilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KargoSilBtnActionPerformed
        // TODO add your handling code here:
        KargoSil ks = new KargoSil();
        ks.setVisible(true);
        YoneticiEkran ye = new YoneticiEkran();
        ye.dispose();
         

    }//GEN-LAST:event_KargoSilBtnActionPerformed

    private void yoneticiEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkleBtnActionPerformed
        YoneticiEkle ye = new YoneticiEkle();
        ye.setVisible(true);
    }//GEN-LAST:event_yoneticiEkleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiEkran().setVisible(true);
            }
        });
    }

    public void table1() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KargoSilBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kargoAraBtn;
    private javax.swing.JTextField kargoAraText;
    private javax.swing.JButton kargoEkleBtn;
    private javax.swing.JButton kargoListeleBtn;
    private javax.swing.JButton kullaniciEkleBtn;
    private javax.swing.JButton kullaniciSilBtn;
    private javax.swing.JButton yoneticiEkleBtn;
    private javax.swing.JTextPane yoneticiEkrKrgBilgiText;
    // End of variables declaration//GEN-END:variables
}
